config/routes.rb
Rails.application.routes.draw do
  resources :todos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :assign_todo, except: %i(index new create)

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to todos_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update_attributes(todo_params)
      redirect_to @todo
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_url
  end

private

  def assign_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:description, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.erb
<nav>
  <%= link_to "Tâches à faire", todos_path %> |
  <%= link_to "Ajouter une tâche", new_todo_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= render 'navigation' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for todo do |f| %>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true %>
    <strong><%= todo.errors[:description].to_sentence %></strong>
  </p>
  <p>
    <%= f.label :notes %>
    <%= f.text_area :notes, rows: 20, cols: 80 %>
  </p>
  <p>
    <%= f.submit submit_label %>
    ou <%= link_to "annuler", cancel_url %>
  </p>
<% end %>

app/views/todos/edit.html.erb
<h1>Édition : <%= @todo.description %></h1>
<%= render "form", todo:         @todo,
                   submit_label: "Enregistrer les modifications",
                   cancel_url:   todo_path(@todo) %>

app/views/todos/index.html.erb
<h1>Tâches à faire</h1>
<ul>
  <% @todos.each do |todo| %>
    <li>
      <%= link_to todo.description, todo %>
    </li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h1>Nouvelle tâche</h1>
<%= render 'form', todo:         @todo,
                   submit_label: "Ajouter cette tâche",
                   cancel_url:   todos_path %>

app/views/todos/show.html.erb
<h1><%= @todo.description %></h1>
<p>
  <% @todo.notes.each_line do |line| %>
    <%= line %><br>
  <% end %>
</p>
<p>
  <strong>
    <%= link_to 'Modifier', [:edit, @todo] %>
  </strong>
  <small>
    ou
    <%= link_to 'supprimer', @todo, method: :delete,
                                    data: {confirm: "Supprimer cette tâche ?"} %>
  </small>
</p>